#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS")]
	public partial class QLNS1DataContext : System.Data.Linq.DataContext
	{
		public QLNS1DataContext() :
			base(global::QLNS.Properties.Settings.Default.QLNSConnectionString, mappingSource)
		{
			OnCreated();
		}
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblBoPhan(TblBoPhan instance);
    partial void UpdateTblBoPhan(TblBoPhan instance);
    partial void DeleteTblBoPhan(TblBoPhan instance);
    partial void InsertTblPhongBan(TblPhongBan instance);
    partial void UpdateTblPhongBan(TblPhongBan instance);
    partial void DeleteTblPhongBan(TblPhongBan instance);
    #endregion
		
		public QLNS1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNS1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNS1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNS1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblBoPhan> TblBoPhans
		{
			get
			{
				return this.GetTable<TblBoPhan>();
			}
		}
		
		public System.Data.Linq.Table<TblPhongBan> TblPhongBans
		{
			get
			{
				return this.GetTable<TblPhongBan>();
			}
		}

        public string MaBoPhan { get; internal set; }
        public string TenBoPhan { get; internal set; }
        public string NgayThanhLap { get; internal set; }
        public string GhiChu { get; internal set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblBoPhan")]
	public partial class TblBoPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBoPhan;
		
		private string _TenBoPhan;
		
		private System.Nullable<System.DateTime> _NgayThanhLap;
		
		private string _GhiChu;
		
		private EntitySet<TblPhongBan> _TblPhongBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBoPhanChanging(string value);
    partial void OnMaBoPhanChanged();
    partial void OnTenBoPhanChanging(string value);
    partial void OnTenBoPhanChanged();
    partial void OnNgayThanhLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhLapChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public TblBoPhan()
		{
			this._TblPhongBans = new EntitySet<TblPhongBan>(new Action<TblPhongBan>(this.attach_TblPhongBans), new Action<TblPhongBan>(this.detach_TblPhongBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoPhan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBoPhan
		{
			get
			{
				return this._MaBoPhan;
			}
			set
			{
				if ((this._MaBoPhan != value))
				{
					this.OnMaBoPhanChanging(value);
					this.SendPropertyChanging();
					this._MaBoPhan = value;
					this.SendPropertyChanged("MaBoPhan");
					this.OnMaBoPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBoPhan", DbType="NChar(10)")]
		public string TenBoPhan
		{
			get
			{
				return this._TenBoPhan;
			}
			set
			{
				if ((this._TenBoPhan != value))
				{
					this.OnTenBoPhanChanging(value);
					this.SendPropertyChanging();
					this._TenBoPhan = value;
					this.SendPropertyChanged("TenBoPhan");
					this.OnTenBoPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThanhLap
		{
			get
			{
				return this._NgayThanhLap;
			}
			set
			{
				if ((this._NgayThanhLap != value))
				{
					this.OnNgayThanhLapChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhLap = value;
					this.SendPropertyChanged("NgayThanhLap");
					this.OnNgayThanhLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NChar(10)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblBoPhan_TblPhongBan", Storage="_TblPhongBans", ThisKey="MaBoPhan", OtherKey="MaBoPhan")]
		public EntitySet<TblPhongBan> TblPhongBans
		{
			get
			{
				return this._TblPhongBans;
			}
			set
			{
				this._TblPhongBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TblPhongBans(TblPhongBan entity)
		{
			this.SendPropertyChanging();
			entity.TblBoPhan = this;
		}
		
		private void detach_TblPhongBans(TblPhongBan entity)
		{
			this.SendPropertyChanging();
			entity.TblBoPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPhongBan")]
	public partial class TblPhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBoPhan;
		
		private string _MaPhong;
		
		private string _TenPhong;
		
		private System.Nullable<System.DateTime> _NgayThanhLap;
		
		private string _GhiChu;
		
		private EntityRef<TblBoPhan> _TblBoPhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBoPhanChanging(string value);
    partial void OnMaBoPhanChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnNgayThanhLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhLapChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public TblPhongBan()
		{
			this._TblBoPhan = default(EntityRef<TblBoPhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoPhan", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MaBoPhan
		{
			get
			{
				return this._MaBoPhan;
			}
			set
			{
				if ((this._MaBoPhan != value))
				{
					if (this._TblBoPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBoPhanChanging(value);
					this.SendPropertyChanging();
					this._MaBoPhan = value;
					this.SendPropertyChanged("MaBoPhan");
					this.OnMaBoPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThanhLap
		{
			get
			{
				return this._NgayThanhLap;
			}
			set
			{
				if ((this._NgayThanhLap != value))
				{
					this.OnNgayThanhLapChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhLap = value;
					this.SendPropertyChanged("NgayThanhLap");
					this.OnNgayThanhLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblBoPhan_TblPhongBan", Storage="_TblBoPhan", ThisKey="MaBoPhan", OtherKey="MaBoPhan", IsForeignKey=true)]
		public TblBoPhan TblBoPhan
		{
			get
			{
				return this._TblBoPhan.Entity;
			}
			set
			{
				TblBoPhan previousValue = this._TblBoPhan.Entity;
				if (((previousValue != value) 
							|| (this._TblBoPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblBoPhan.Entity = null;
						previousValue.TblPhongBans.Remove(this);
					}
					this._TblBoPhan.Entity = value;
					if ((value != null))
					{
						value.TblPhongBans.Add(this);
						this._MaBoPhan = value.MaBoPhan;
					}
					else
					{
						this._MaBoPhan = default(string);
					}
					this.SendPropertyChanged("TblBoPhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
